# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: KOO JEONG YEON
title: Backend Developer (1996.02)
email: noey458749@gmail.com
# email_title: Email (Email title override)
phone: 
# phone_title: Phone (Phone title override)
website: https://koojeongyeons-engineering-wiki.gitbook.io/engineering-wiki/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  koo-jeongyeon
stackoverflow_username: 
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: 
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 
googlescholar_username: 

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: #Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 을 주력으로 개발해온 백엔드 개발자 구정연입니다.
  소셜, 크라우드펀딩, 에듀테크 등의 서비스에서 백엔드 플랫폼 개발 및 서버 인프라 구축 등을 수행했으며 다양한 개발환경에서의 경험을 기반으로 새로운 환경에 적응이 빠른 편입니다. 
  개발 커리어를 쌓기 위해 아르바이트부터 경험을 쌓기 시작하여 끊임없이 일을 지속해왔습니다. 어려운 문제에 부딫히더라도 끈기있게 해결해나가는 자세가 중요하다는 신념하에 새로운 개발을 즐깁니다.

content:
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Language
        description: |
          - Java(JSP,VUE), JavaScript
      - layout: left
        title: Framework & Library
        description: |
          - Spring Boot_(JPA, Querydsl, Hibernate, JWT, Security, JUnit, Cloud AWS)
      - layout: left
        title: Database
        description: |
          - MySQL, Mssql, MongoDB(atlas), H2 Database
      - layout: left
        title: DevOps
        description: |
          - AWS_(EC2, ELB(beanstalk), ECR, Route53, Lambda, S3)
          - Ubuntu, Apache Tomcat, Docker
          - Elastic Cloud_(filebeat, logstash, Kibana)
      - layout: left
        title: ETC
        description: |
          - Git_(Github, Gitlab) Jira, Slack, Trello, Notion, IntelliJ, Visual Studio Code
  - title: Career
    layout: list
    content:
      - layout: left
        title: DotDotDot(닫닫닫)
        sub_title: Java & Spring 백엔드 개발자
        caption: 2022.10 - 2023.04 (6개월)
        quote: >
          메타버스 기반의 소셜미디어 앱 서비스
        description: |
          신규 소셜미디어 앱 서비스 출시를 위해 백엔드 개발팀에 합류하게 되었습니다. 앱의 회원과 컨텐츠관리를 위한 API개발과 서버 인프라 구축 및 예러코드를 정의하고 문서화하며 예외처리 전략을 적용하였습니다. 
          또한 로그 모니터링을 위한 인프라를 세팅하여 전사 테스트시 에러로그를 테이블 형태로 빠르게 확인할 수 있도록 하였습니다.

          - Java17(Spring, Vue, Gradle, MongoDB atlas), AWS, Docker, Elastic Cloud, Git(Gitlab), Jira
      - layout: left
        title: 루트에너지
        sub_title: Java & Spring 백엔드 개발자
        caption: 2021.09 - 2022.09 (1년)
        quote: >
          재생에너지 크라우드펀딩 플랫폼 서비스
        description: |
          서비스중인 크라우드펀딩 플랫폼의 데이터로 외부 솔루션 API와 연동한 배치 프로젝트 개발과 원리금수취권 거래 테스트를 위한 서버 인프라 구축을 진행 하였습니다. 

          - Java8(Spring, JSP, Gradle, Mysql), GCP, Ubuntu, Tomcat, Git(Gitlab), Slack, Notion
      - layout: left
        title: 에듀랩
        sub_title: 웹개발자
        caption: 2020.08 - 2021.08 (1년)
        quote: >
          게임기반 아동용 학습 서비스를 제공하는 에듀테크
        description: |
          신규 저학년 학습용 서비스의 하이브리드앱 전체 기능 개발과 유지보수, 학습용 게임 스크립트의 버그 수정을 수행했습니다.

          - Java8(Spring, JSP, Maven, Mssql), JavaScript(JQuery), Git(Github)
      - layout: left
        title: 블랜딩 
        sub_title: |
          [파트타임] 게임 개발자
        caption: 2019.03 - 2020.05 (1년2개월)
        quote: >
          웹 사이트 및 미니 게임 개발 서비스를 제공하는 SI
        description: |
          파트타임으로 카드게임과 브루마블 게임 클라이언트 및 서버 개발, 유지보수를 진행하며 자바 스프링 개발자로 커리어를 쌓는 계기가 되었습니다.

          - Java8(전자정부 Spring, Maven, Mysql), JavaScript(JQuery), Unity, SVN
  - title: DotDotDot(닫닫닫)
    layout: text
    content: 
      - sub_title: 차후 운영을 위한 소셜미디어 앱의 운영툴 서비스 세팅 및 구축 (3개월/2023.02~2023.04)
        description: | 
          - 개발환경: Java(Spring Boot,Vue), MongoDB atlas
          - 유저관리와 유저의 컨텐츠 수정 및 삭제, 벤처리를 위한 초기 운영툴 개발을 위해 Spring Boot와 Vue3세팅,
          Security를 적용해 관리자가 접근할 수 있는 페이지 및 기능에 등급별로 제한을 두도록 구현, JWT 토큰을 활용하여 관리자의 회원가입 로그인 구현
      - sub_title: 디바이스에 캐시된 S3리소스의 갱신과 S3업로드에 실패한 컨텐츠 리소스 재업로드 기능 구현 (2개월/2023.01,2023.04)
        description: | 
          - 개발환경: Node.js, MongoDB atlas, AWS(S3,SAM,Lambda), Unity
          - 컨텐츠를 생성할 때 디바이스에 캐시가 저장되고 S3에 리소스가 업로드되는 구조로,
          다수의 디바이스 이용시 한 디바이스에서 컨텐츠 업데이트때에 다른 디바이스의 로컬 캐시도 S3업로드 된것 기준으로 캐시를 업데이트하는 기능 구현을 위해
          데이터베이스에 S3에 리소스가 업데이트되는 Date를 저장해야함. 또한 데이터베이스에 먼저 업데이트 날짜가 기록된 이후 S3에 업로드 되는 구조로 앞서 Date를 저장해야 S3업로드 실패 여부도 확인가능하였음.
          - S3에 리소스가 업데이트 되는 시점에 Lambda를 실행하여 MongoDB atlas에 직접 접근해 업데이트함. Lambda를 로컬에서 실행하고 배포하기 위해 AWS SAM을 활용.
          - Lambda가 MongoDB atlas와 S3에 접근해야하기 때문에 VPC에 MongoDB atlas와 peering으로 연결해주고 S3는 private subnet에 접근하지 못하는 문제가 있어 VPC endpoint설정을 해줌.
      - sub_title: 신규 소셜미디어 앱 서비스의 API서버 로그를 핸들링하여 키바나에서 테이블 형태로 바로 확인할 수 있도록 구현 및 서버 인프라 구축 (2개월/2022.11~2022.12)
        description: | 
          - 개발환경 : Java(Spring Boot), Elastic Cloud(filebeat, logstash, Kibana), AWS(Beanstalk,ECR), Docker
          - Elastic Cloud의 무료버전(2주)을 가입하여 배포를 생성, AWS ECR에 Jar,filebeat,logstash의 Docker Image 업로드하여 docker-compose로 Jar&filebeat와 logstash따로 AWS Beanstalk에 배포.
          - Jar파일의 로그를 volume으로 filebeat와 공유하여 logstash로 전송. logstash는 elastic cloud로 로그를 전송하는 세팅을 적용하여 kibana에 테이블형태로 로그 확인.
          - 배포시 이전 로그들이 다시 처음부터 filebeat를 통해 kibana에 업로드되어 부하를 발생시켰음. filebeat의 레지스트리에 volume설정을 해주어 로그파일을 어디까지 파일을 읽었는지 유실되지 않도록 조치를 취함.
          - logstash를 Beanstalk에 배포하여 ip가 고정되지 않는 문제가 있어 로드밸런서 유형을 network load balancer 로 설정하고 로드밸런서로 filebeat데이터 전송.
          - 서버에 AOP를 적용후 logstash-logback-encoder로 전체 비즈니스 로직 로그 생성하여 kibana 테이블에 보여주고 싶은 로그 컬럼 선별하여 보여줌.
      - sub_title: 신규 소셜미디어 앱 서비스의 API서버 에러코드 정의후 예외처리 전략을 적용하여 개발 환경개선 (1개월/2022.10~2022.10)
        description: | 
          - 개발환경 : Java(Spring Boot)
          - 비즈니스 로직의 에러코드를 한곳에서 관리하기 위해 ErrorCode를 정의하는 enum을 생성하고 RuntimeException을 상속받는 ApiException클래스를 만들어 @ExceptionHandler를 사용해 
          의도적인 에러 발생 조건에 부합할시 ErrorCode를 매개변수로 하는 ApiException를 throw 처리. 
          ApiExceptionHandler 클래스를 생성하여 @RestControllerAdvice를 사용해 Response body에 Json형태로 에러코드와 메시지를 리턴하도록 구현.
  - title: 루트에너지
    layout: text
    content: 
      - sub_title: 크라우드 펀딩 플랫폼의 코드 분석 및 유지보수업무 (10개월/2021.11~2022.09)
        description: | 
          - 개발환경 : Java(Spring Boot), Mysql
          - 외부 솔루션 업체에서 제작한 플랫폼의 코드분석을 위해 담당자와 커뮤니케이션하며 소스코드를 파악해 문서로 정리. 
          외부팀에서 매달 금결원에 제출해야하는 자료에 필요한 데이터 추출작업 담당. 이후 반복되는 작업들은 @Scheduler로 배치 서비스로 개발하여 담당자 메일로 발송되도록 개선.
      - sub_title: 크라우드 펀딩 플랫폼의 원리금수취권 거래 기능 테스트를 위한 인프라 구축 및 테스트 (2개월/2022.07~2022.08)
        description: | 
          - 개발환경 : GCP, Ubuntu, Tomcat
          - 여유분의 사내 데스크탑에 Ubuntu 설치 및 Apache Tomcat으로 플랫폼의 war파일 배포 가능하도록 세팅. 금결원 테스트API 사용을 위해 솔루션업체와 금결원과 커뮤니케이션.
          - 원리금수취권 거래 기능의 테스트케이스를 작성하여 팀원들에게 배포하고 테스트 진행.
      - sub_title: 크라우드 펀딩 플랫폼의 자금세탁방지(AML)솔루션 구축을 위한 배치 서비스 개발 (1개월/2021.10~2021.10)
        description: | 
          - 개발환경 : Java(Spring Boot), GCP
          - 새로가입한 회원들의 고객확인절차(KYC)가 필요해 외부 솔루션 업체의 API로 고객정보를 전달하는 배치 서비스를 @Scheduler를 활용해 개발. 매일 특정시간에 외부 AML솔루션 업체에 내부 데이터 적재하는 배치 서비스 개발.
          - GCP에 배치 서비스 배포 인프라 구축 내부망 데이터베이스에 접근하기 위해 vpn연결이 필요해 openfortivpn을 활용해 연결. 서버의 크론탭에 매시간 vpn연결을 체크하여 연결이 끊기면 다시 연결되도록 쉘 스크립트 작성.
  - title: 에듀랩
    layout: text
    content: 
      - sub_title: 신규 저학년 대상 학습용 하이브리드 앱의 API서버 개발 및 프런트 개발 (5개월/2020.10~2021.02)
        description: | 
          - 개발환경 : Java(Spring), JavaScript(JQuery), Mssql
          - 저학년을 대상으로 한 학습용 앱의 2차버전 개발과 학생들의 학습내역을 조회 및 그래프로 확인할 수 있는 앱의 서버API 개발과 화면 렌더링 구현, ERD구상하여 테이블 구현. 네이티브 앱 개발자와 협업을 진행 하였으며 브릿치 추가 작업.
          학습을 위한 화면 레이아웃 html파일 받아서 JSP로 작업. 이미지,음성 등의 비정형데이터 서버에 업로드하고 앱에서 조회,수정,삭제 하는 등 기본적인 CRUD 구현.
          - 학습 컨텐츠는 개월별로 계속해서 생성되고 업데이트 되기 때문에 화면단의 jsp파일이 방대하게 늘어나지 않도록 최대한 재사용이 가능하도록 화면단 구현. 컨텐츠를 하나하나 파일질라로 서버에 업로드 하는 방식이 비효율적이라 생각해 
          기획애 없더라도 남는 시간에 운영을 위한 컨텐츠 업로드 툴을 추가로 개발함. 컨텐츠 업로드시 많은 시간을 단축.
      - sub_title: 신규 저학년 대상 학습용 하이브리드 앱의 팝업 구현 및 유지보수 (7개월/2021.02~2021.08)
        description: | 
          - 개발환경 : Java(Spring), JavaScript(JQuery), Mssql
          - 버전정보를 체크하여 디바이스와 디비의 버전이 다르면 점검 및 업데이트 팝업이 호출되도록 구현. @Scheduler로 30분간격으로 버전 체크 실행. 공지사항의 추가 개발과 유지보수 진행.
  - title: 블랜딩
    layout: text
    content: 
      - sub_title: 유니티를 기반으로한 4인 멀티플레이 게임 개발 및 수정 (12개월/2019.04~2020.04)
        description: | 
          - 개발환경 : Java(Spring), WebSocket, Unity, Mysql
          - 웹에서 이더리움을 충전하여 게임에서 4인 멀티플레이 게임을 진행하는 방식으로 훌라와 브루마블 등의 게임 제작. WebSocket으로 서버와 Unity클라이언트간 json형태 패킷 통신을 구현.
          유저가 접속하면 WebSocketSession에 세션값 저장하여 Socket handler에서 입장과 퇴장시 초기화 로직 실행. 
          - 클라이언트에서 4인팟 Room입장시 서버로 해당 데이터 json패킷 전송, 해당 룸클래스의 유저배열에 추가하여 2이상 모이면 게임시작버튼 생성.
          유저가 해당 턴에 액션을 취했을시 방에 있는 모든 유저들에게도 해당 액션에 대해 서버에서 json패킷을 전송해 동기화, 클라이언트에서 확인 가능하도록 애니메이션 개발.
          턴마다 시간제한을 두고 시간제한이 넘어갈 시 패스하도록 구현하는 등의 게임 로직 구현을 담당.
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: plantRow
  #       link: https://github.com/koo-jeongyeon/PlantRow
  #       link_text: https://github.com/koo-jeongyeon/PlantRow
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: https://github.com/koo-jeongyeon/PlantRow
  #       # quote: >
  #       #   Short overview of the project (optional)
  #       description: |
  #         `JAVA` `Spring Boot`

  #         식물의 물주기와 영양을 관리하는 사이트
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: catblockGame
  #       link: https://github.com/koo-jeongyeon/catblockgame
  #       link_text: https://github.com/koo-jeongyeon/catblockgame
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: https://github.com/koo-jeongyeon/catblockgame
  #       description: 고양이 블럭
  - title: Education
    layout: text
    content:
      - sub_title: 
        description: | 
          - [2018 - 현재] 한국방송통신대학교 컴퓨터과학과 (2024년 졸업예정)
          - [2017] 국비지원학원 구디아카데미 수료

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
